### ISSUE TITLE
./ide.sh build fail

### ISSUE THREAD

**Issue by jnan77** [Coding/WebIDE#15]
console
```
> NODE_ENV=production ./node_modules/webpack/bin/webpack.js

sh: ./node_modules/webpack/bin/webpack.js: 权限不够

npm ERR! Linux 3.10.0-327.el7.x86_64
npm ERR! argv "/www/env/node/bin/node" "/www/env/node/bin/npm" "run" "build"
npm ERR! node v0.12.10
npm ERR! npm  v2.14.9
npm ERR! code ELIFECYCLE
npm ERR! coding-web-ide@1.0.0 build: `NODE_ENV=production ./node_modules/webpack/bin/webpack.js`
npm ERR! Exit status 126
npm ERR!
npm ERR! Failed at the coding-web-ide@1.0.0 build script 'NODE_ENV=production ./node_modules/webpack/bin/webpack.js'.
npm ERR! This is most likely a problem with the coding-web-ide package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production ./node_modules/webpack/bin/webpack.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls coding-web-ide
npm ERR! There is likely additional logging output above.
```
log
```
10 verbose stack     at EventEmitter.<anonymous> (/www/env/node-v0.12.10-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/www/env/node-v0.12.10-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1016:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1088:5)
11 verbose pkgid coding-web-ide@1.0.0
12 verbose cwd /www/webroot/ide.ginlink.com/WebIDE/frontend
13 error Linux 3.10.0-327.el7.x86_64
14 error argv "/www/env/node/bin/node" "/www/env/node/bin/npm" "run" "build"
15 error node v0.12.10
16 error npm  v2.14.9
17 error code ELIFECYCLE
18 error coding-web-ide@1.0.0 build: `NODE_ENV=production ./node_modules/webpack/bin/webpack.js`
18 error Exit status 126
19 error Failed at the coding-web-ide@1.0.0 build script 'NODE_ENV=production ./node_modules/webpack/bin/webpack.js'.
19 error This is most likely a problem with the coding-web-ide package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     NODE_ENV=production ./node_modules/webpack/bin/webpack.js
19 error You can get their info via:
19 error     npm owner ls coding-web-ide
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
```

**Comment by summershrimp** [comment]
try   
```
chmod +x ./node_modules/webpack/bin/webpack.js
```
看上去是在npm安装webpack时没有为相关文件添加可执行权限

**Comment by jnan77** [comment]
加了之后又出现下面的信息了，但是成功了
```
ERROR in Cannot find module 'core-js/library/fn/symbol/iterator'
```

**Comment by hackape** [comment]
@jnan77 下午更新了一把:
```
cd ./frontend
```

**Comment by hackape** [comment]
另外最好用最新版本的 node v6.x 避免疑难杂症。
