### ISSUE TITLE
切换主题报错

### ISSUE THREAD

**Issue by qixin1991** [Coding/WebIDE#165]
IP正常打开后，修改主题会报错

```
main.53618da….js:1 Uncaught TypeError: Cannot read property 'Light' of undefined
    at i (http://172.20.9.1:9090/rs/main.53618da69e0740089e7f.js:1:1000999)
    at http://172.20.9.1:9090/rs/main.53618da69e0740089e7f.js:1:552410
    at http://172.20.9.1:9090/rs/main.53618da69e0740089e7f.js:1:350579
    at http://172.20.9.1:9090/rs/main.53618da69e0740089e7f.js:1:523276
    at Array.reduce (native)
    at http://172.20.9.1:9090/rs/main.53618da69e0740089e7f.js:1:523248
    at http://172.20.9.1:9090/rs/main.53618da69e0740089e7f.js:1:525602
    at http://172.20.9.1:9090/rs/vendor.8cd39b7703aa4ad84d7c.js:1:315656
    at http://172.20.9.1:9090/rs/main.53618da69e0740089e7f.js:1:368085
    at Array.reduceRight (native)
```

**Comment by hackape** [comment]
目标已变更为建一个新的黑色主题
