### ISSUE TITLE
error: cannot run ssh: No such file or directory 

### ISSUE THREAD

**Issue by xiangnanscu** [Coding/WebIDE#203]
通过命令`docker run -p 8080:8080 --name webide webide/webide`, 之后输入了码云的git地址,成功创建了workspace, 但是我准备pull一个分支时, 这样提示:
```
working-dir git:(test) git pull origin es6                                                                                                                                                                           
error: cannot run ssh: No such file or directory                                                                                                                                                                        
fatal: unable to fork
```
我该怎么做呢

**Comment by pronan** [comment]
我发现浏览器的console提示加载失败了一些url, 不知是不是和这个有关:
```
GET http://domain.cn:8080/packages 404 ()
(anonymous) @ main.1d90af0….js:1
e.exports @ main.1d90af0….js:1
e.exports @ main.1d90af0….js:1
main.1d90af0….js:1 Uncaught (in promise) Error: No message available
    at e.exports (http://domain.cn:8080/rs/main.1d90af0e5e3c7ff8a7db.js:1:405684)
    at e.exports (http://domain.cn:8080/rs/main.1d90af0e5e3c7ff8a7db.js:1:467157)
    at XMLHttpRequest.p.(anonymous function) (http://domain.cn:8080/rs/main.1d90af0e5e3c7ff8a7db.js:1:404433)
e.exports @ main.1d90af0….js:1
e.exports @ main.1d90af0….js:1
p.(anonymous function) @ main.1d90af0….js:1
vendor.fe5169e….js:1 Uncaught Error: Actions must be plain objects. Use custom middleware for async actions.
    at p (http://domain.cn:8080/rs/vendor.fe5169ec1277ef51f69d.js:1:140098)
    at http://domain.cn:8080/rs/main.1d90af0e5e3c7ff8a7db.js:1:1100216
    at http://domain.cn:8080/rs/main.1d90af0e5e3c7ff8a7db.js:1:646078
    at http://domain.cn:8080/rs/main.1d90af0e5e3c7ff8a7db.js:1:909285
    at i.onmessage (http://domain.cn:8080/rs/main.1d90af0e5e3c7ff8a7db.js:1:1515324)
    at i.r.dispatchEvent (http://domain.cn:8080/rs/main.1d90af0e5e3c7ff8a7db.js:1:863509)
    at http://domain.cn:8080/rs/main.1d90af0e5e3c7ff8a7db.js:1:1492357
    at Array.forEach (native)
    at i._transportMessage (http://domain.cn:8080/rs/main.1d90af0e5e3c7ff8a7db.js:1:1492308)
    at r.emit (http://domain.cn:8080/rs/main.1d90af0e5e3c7ff8a7db.js:1:373519)
```

**Comment by vangie** [comment]
问题已经重现，会在下一版本修复，谢谢您的反馈！
