### ISSUE TITLE
ubuntu server 16.04 x86_64 build失败,该如何解决?

### ISSUE THREAD

**Issue by cxgreat2014** [Coding/WebIDE#21]
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
building frontend...

> coding-web-ide@1.0.0 build /home/hook/WebIDE/frontend
> cross-env NODE_ENV=production ./node_modules/webpack/bin/webpack.js --progress --colors

/usr/bin/env: "node": 没有那个文件或目录

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! coding-web-ide@1.0.0 build: `cross-env NODE_ENV=production ./node_modules/webpack/bin/webpack.js --progress --colors`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the coding-web-ide@1.0.0 build script 'cross-env NODE_ENV=production ./node_modules/webpack/bin/webpack.js --progress --colors'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the coding-web-ide package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production ./node_modules/webpack/bin/webpack.js --progress --colors
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs coding-web-ide
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls coding-web-ide
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/hook/WebIDE/frontend/npm-debug.log

**Comment by cxgreat2014** [comment]
root@ubuntu:/home/hook/WebIDE# cat /home/hook/WebIDE/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'bugs', 'coding-web-ide' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 silly fetchPackageMetaData coding-web-ide
5 silly fetchNamedPackageData coding-web-ide
6 silly mapToRegistry name coding-web-ide
7 silly mapToRegistry using default registry
8 silly mapToRegistry registry https://registry.npmjs.org/
9 silly mapToRegistry uri https://registry.npmjs.org/coding-web-ide
10 verbose request uri https://registry.npmjs.org/coding-web-ide
11 verbose request no auth needed
12 info attempt registry request try #1 at 上午11:44:48
13 verbose request id 27b6fda3a5fbaae7
14 http request GET https://registry.npmjs.org/coding-web-ide
15 http 404 https://registry.npmjs.org/coding-web-ide
16 verbose headers { 'content-type': 'application/json',
16 verbose headers   'cache-control': 'max-age=0',
16 verbose headers   'content-length': '2',
16 verbose headers   'accept-ranges': 'bytes',
16 verbose headers   date: 'Wed, 21 Sep 2016 03:47:17 GMT',
16 verbose headers   via: '1.1 varnish',
16 verbose headers   age: '0',
16 verbose headers   connection: 'keep-alive',
16 verbose headers   'x-served-by': 'cache-sin6922-SIN',
16 verbose headers   'x-cache': 'MISS',
16 verbose headers   'x-cache-hits': '0',
16 verbose headers   'x-timer': 'S1474429637.177396,VS0,VE269',
16 verbose headers   vary: 'Accept-Encoding' }
17 silly get cb [ 404,
17 silly get   { 'content-type': 'application/json',
17 silly get     'cache-control': 'max-age=0',
17 silly get     'content-length': '2',
17 silly get     'accept-ranges': 'bytes',
17 silly get     date: 'Wed, 21 Sep 2016 03:47:17 GMT',
17 silly get     via: '1.1 varnish',
17 silly get     age: '0',
17 silly get     connection: 'keep-alive',
17 silly get     'x-served-by': 'cache-sin6922-SIN',
17 silly get     'x-cache': 'MISS',
17 silly get     'x-cache-hits': '0',
17 silly get     'x-timer': 'S1474429637.177396,VS0,VE269',
17 silly get     vary: 'Accept-Encoding' } ]
18 silly fetchPackageMetaData Error: Registry returned 404 for GET on https://registry.npmjs.org/coding-web-ide
18 silly fetchPackageMetaData     at makeError (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:264:12)
18 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:242:14)
18 silly fetchPackageMetaData     at Request._callback (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:172:14)
18 silly fetchPackageMetaData     at Request.self.callback (/usr/share/npm/node_modules/request/request.js:198:22)
18 silly fetchPackageMetaData     at emitTwo (events.js:87:13)
18 silly fetchPackageMetaData     at Request.emit (events.js:172:7)
18 silly fetchPackageMetaData     at Request.<anonymous> (/usr/share/npm/node_modules/request/request.js:1082:10)
18 silly fetchPackageMetaData     at emitOne (events.js:82:20)
18 silly fetchPackageMetaData     at Request.emit (events.js:169:7)
18 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/usr/share/npm/node_modules/request/request.js:1009:12)
18 silly fetchPackageMetaData  error for coding-web-ide { [Error: Registry returned 404 for GET on https://registry.npmjs.org/coding-web-ide] pkgid: 'coding-web-ide', statusCode: 404, code: 'E404' }
19 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/coding-web-ide
19 verbose stack     at makeError (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:264:12)
19 verbose stack     at CachingRegistryClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:242:14)
19 verbose stack     at Request._callback (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:172:14)
19 verbose stack     at Request.self.callback (/usr/share/npm/node_modules/request/request.js:198:22)
19 verbose stack     at emitTwo (events.js:87:13)
19 verbose stack     at Request.emit (events.js:172:7)
19 verbose stack     at Request.<anonymous> (/usr/share/npm/node_modules/request/request.js:1082:10)
19 verbose stack     at emitOne (events.js:82:20)
19 verbose stack     at Request.emit (events.js:169:7)
19 verbose stack     at IncomingMessage.<anonymous> (/usr/share/npm/node_modules/request/request.js:1009:12)
20 verbose statusCode 404
21 verbose pkgid coding-web-ide
22 verbose cwd /home/hook/WebIDE
23 error Linux 4.4.0-31-generic
24 error argv "/usr/bin/nodejs" "/usr/bin/npm" "bugs" "coding-web-ide"
25 error node v4.2.6
26 error npm  v3.5.2
27 error code E404
28 error 404 Registry returned 404 for GET on https://registry.npmjs.org/coding-web-ide
29 error 404
30 error 404 'coding-web-ide' is not in the npm registry.
31 error 404 You should bug the author to publish it (or use the name yourself!)
32 error 404 Note that you can also install from a
33 error 404 tarball, folder, http url, or git url.
34 verbose exit [ 1, true ]

**Comment by hackape** [comment]
确认两件事：
1. 服务器上命令行运行 `/usr/bin/env node` 看看 node 是不是能开
2. 到 frontend 的 package.json 把 "scripts.build" 字段改为：
`NODE_ENV=production ./node_modules/webpack/bin/webpack.js --progress --colors`

做完麻烦给我个反馈

**Comment by cxgreat2014** [comment]
node能开,pkgjson等会反馈

**Comment by cxgreat2014** [comment]
ok,成功运行,我去试试看docker能不能构建

**Comment by cxgreat2014** [comment]
啊咧..又出怪事了

2016-09-21 22:50:34.449  WARN 812 --- [ost-startStop-2] o.a.c.loader.WebappClassLoaderBase       : Failed to check for ThreadLocal references for web application [ROOT]

java.lang.UnsupportedOperationException: null
	at com.zaxxer.hikari.util.FastList.iterator(FastList.java:209)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadedByThisOrChild(WebappClassLoaderBase.java:1986)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks(WebappClassLoaderBase.java:1890)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalsForLeaks(WebappClassLoaderBase.java:1844)
	at org.apache.catalina.loader.WebappClassLoaderBase.clearReferences(WebappClassLoaderBase.java:1514)
	at org.apache.catalina.loader.WebappClassLoaderBase.stop(WebappClassLoaderBase.java:1460)
	at org.apache.catalina.loader.WebappLoader.stopInternal(WebappLoader.java:447)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:229)
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5436)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:229)
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1419)
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1408)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2016-09-21 22:50:34.467  WARN 812 --- [           main] o.s.boot.SpringApplication               : Error handling failed (Error creating bean with name 'eventExchange' defined in file [/root/WebIDE/backend/target/classes/net/coding/ide/web/message/EventExchange.class]: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry' is defined)
2016-09-21 22:50:34.525 ERROR 812 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Exception during pool initialization: HikariPool-0 - Connection is not available, request timed out after 30007ms.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1076)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:851)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
	at net.coding.ide.Application.main(Application.java:31)
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Exception during pool initialization: HikariPool-0 - Connection is not available, request timed out after 30007ms.
	at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:526)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:136)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:94)
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:139)
	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcServicesImpl.java:279)
	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:124)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:111)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:234)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:206)
	at org.hibernate.cfg.Configuration.buildTypeRegistrations(Configuration.java:1887)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1845)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:857)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:850)
	at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.withTccl(ClassLoaderServiceImpl.java:425)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:849)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:60)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:338)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:373)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:362)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
	... 16 common frames omitted
Caused by: java.sql.SQLTransientConnectionException: HikariPool-0 - Connection is not available, request timed out after 30007ms.
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:195)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
	at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:510)
	... 36 common frames omitted
Caused by: java.sql.SQLException: path to '/root/.coding-ide-home/ide.db': '/root/.coding-ide-home' does not exist
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:192)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.JDBC.connect(JDBC.java:88)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:314)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:171)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:436)
	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:65)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:567)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:560)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:18 min
[INFO] Finished at: 2016-09-21T22:50:34+00:00
[INFO] Final Memory: 47M/247M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.4.0.RELEASE:run (default-cli) on project backend: Could not exec java: Application finished with non-zero exit code: 1 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by cxgreat2014** [comment]
还是不行,最后的日志:
> coding-web-ide@1.0.0 build /opt/coding/WebIDE/frontend
> cross-env NODE_ENV=production ./node_modules/webpack/bin/webpack.js --progress --colors

Hash: 544aceb991a45c89d681
Version: webpack 1.13.2
Time: 23916ms
      Asset       Size  Chunks             Chunk Names
    main.js    3.34 MB       0  [emitted]  main
     1.1.js     6.9 MB       1  [emitted]  
 index.html  753 bytes          [emitted]  
favicon.ico    4.29 kB          [emitted]  
   [0] multi main 40 bytes {0} [built]
    + 906 hidden modules
Child html-webpack-plugin for "index.html":
        + 3 hidden modules
packing frontend....
[ERROR] Could not create local repository at /home/coding/.m2/repository -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LocalRepositoryNotAccessibleException                                                                                                                                                                       
npm install...
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
building frontend...

> coding-web-ide@1.0.0 build /opt/coding/WebIDE/frontend
> cross-env NODE_ENV=production ./node_modules/webpack/bin/webpack.js --progress --colors

Hash: 544aceb991a45c89d681
Version: webpack 1.13.2
Time: 16169ms
      Asset       Size  Chunks             Chunk Names
    main.js    3.34 MB       0  [emitted]  main
     1.1.js     6.9 MB       1  [emitted]  
 index.html  753 bytes          [emitted]  
favicon.ico    4.29 kB          [emitted]  
   [0] multi main 40 bytes {0} [built]
    + 906 hidden modules
Child html-webpack-plugin for "index.html":
        + 3 hidden modules
packing frontend....
[root@localhost WebIDE]# ./ide.sh docker logs
CRITICAL - webide is not running.

**Comment by cxgreat2014** [comment]
希望尽早提供官方镜像, 唉...折腾三天了, 还是没见着

**Comment by tanhe123** [comment]
官方镜像已经上传到 docker hub，请参考 [readme](https://github.com/Coding/WebIDE/blob/master/README-zh.md)
