### ISSUE TITLE
ide.sh run 失败，错误信息如下

### ISSUE THREAD

**Issue by enhui52125** [Coding/WebIDE#23]
刚启动时：
```
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for net.coding.ide:backend:jar:0.1.1-SNAPSHOT
[WARNING] 'dependencies.dependency.systemPath' for com.pty4j:pty:jar should not point at files within the project directory, ${basedir}/lib/pty4j-0.5.jar will be unresolvable by dependent projects @ line 320, column 25
[WARNING] 'dependencies.dependency.systemPath' for net.java.dev.jna:jna:jar should not point at files within the project directory, ${basedir}/lib/jna.jar will be unresolvable by dependent projects @ line 328, column 25
[WARNING] 'dependencies.dependency.systemPath' for platform:platform:jar should not point at files within the project directory, ${basedir}/lib/jna-platform.jar will be unresolvable by dependent projects @ line 336, column 25
[WARNING] 'dependencies.dependency.systemPath' for com.sparetimelabs:purejavacomm:jar should not point at files within the project directory, ${basedir}/lib/purejavacomm-0.0.17.jar will be unresolvable by dependent projects @ line 344, column 25
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]

```
之后：
```
2016-09-22 15:02:34.142  INFO 3707 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-0 - is starting.
2016-09-22 15:03:04.205  INFO 3707 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-0 - is closing down.
2016-09-22 15:03:07.634  WARN 3707 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Exception during pool initialization: HikariPool-0 - Connection is not available, request timed out after 30012ms.
2016-09-22 15:03:07.637  INFO 3707 --- [           main] o.apache.catalina.core.StandardService   : Stopping service Tomcat
2016-09-22 15:03:07.672  WARN 3707 --- [ost-startStop-2] o.a.c.loader.WebappClassLoaderBase       : Failed to check for ThreadLocal references for web application [ROOT]

java.lang.UnsupportedOperationException: null
        at com.zaxxer.hikari.util.FastList.iterator(FastList.java:209)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadedByThisOrChild(WebappClassLoaderBase.java:1986)
        at org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks(WebappClassLoaderBase.java:1890)
        at org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalsForLeaks(WebappClassLoaderBase.java:1844)
        at org.apache.catalina.loader.WebappClassLoaderBase.clearReferences(WebappClassLoaderBase.java:1514)
        at org.apache.catalina.loader.WebappClassLoaderBase.stop(WebappClassLoaderBase.java:1460)
        at org.apache.catalina.loader.WebappLoader.stopInternal(WebappLoader.java:447)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:229)
        at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5436)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:229)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1419)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1408)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

2016-09-22 15:03:07.695  WARN 3707 --- [           main] o.s.boot.SpringApplication               : Error handling failed (Error creating bean with name 'eventExchange' defined in file [/usr/local/enhui/WebIDE/backend/target/classes/net/coding/ide/web/message/EventExchange.class]: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry' is defined)
2016-09-22 15:03:07.709 ERROR 3707 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Exception during pool initialization: HikariPool-0 - Connection is not available, request timed out after 30012ms.
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1076)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:851)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:313)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
        at net.coding.ide.Application.main(Application.java:31)
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Exception during pool initialization: HikariPool-0 - Connection is not available, request timed out after 30012ms.
        at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:526)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:136)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:94)
        at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:139)
        at org.hibernate.engine.jdbc.internal.JdbcServicesImpl$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcServicesImpl.java:279)
        at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:124)
        at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:111)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:234)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:206)
        at org.hibernate.cfg.Configuration.buildTypeRegistrations(Configuration.java:1887)
        at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1845)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:857)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:850)
        at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.withTccl(ClassLoaderServiceImpl.java:425)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:849)
        at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:60)
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:338)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:373)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:362)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
        ... 16 common frames omitted
Caused by: java.sql.SQLTransientConnectionException: HikariPool-0 - Connection is not available, request timed out after 30012ms.
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:195)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
        at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:510)
        ... 36 common frames omitted
Caused by: java.sql.SQLException: path to '/root/.coding-ide-home/ide.db': '/root/.coding-ide-home' does not exist
        at org.sqlite.core.CoreConnection.open(CoreConnection.java:192)
        at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
        at org.sqlite.JDBC.createConnection(JDBC.java:114)
        at org.sqlite.JDBC.connect(JDBC.java:88)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:314)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:171)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:436)
        at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:65)
        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:567)
        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:560)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:44 min
[INFO] Finished at: 2016-09-22T15:03:07+08:00
```

**Comment by vangie** [comment]
'/root/.coding-ide-home' 目录存在，手工创建一下

**Comment by tanhe123** [comment]
请问这是通过什么方式启动的呢，docker 吗？

**Comment by enhui52125** [comment]
就是通过./ide.sh run启动的，没有使用docker

**Comment by tanhe123** [comment]
方案1. 手动创建目录 /root/.coding-ide-home
方案2. WebIDE-Backend@e7697091bd639560673101b55e32ed37c2cb5de9 应该已经修复了 
，怀疑是没有更新代码, 尝试 `cd backend && git pull`

**Comment by enhui52125** [comment]
哈 完美解决！我要去好好体验体验了，谢谢！
