### ISSUE TITLE
Uncaught Error: Cannot find module "!!./../../node_modules/css-loader/index.js?sourceMap!./../../node_modules/sass-loader/index.js?sourceMap!./main.scss"

### ISSUE THREAD

**Issue by likunyan** [Coding/WebIDE#4]
Uncaught Error: Cannot find module "!!./../../node_modules/css-loader/index.js?sourceMap!./../../node_modules/sass-loader/index.js?sourceMap!./main.scss"

build后，run提示这个错误，不是前端的不懂这些，大大帮忙看看。

**Comment by likunyan** [comment]
我运行下npm install lodash.isequal --save-dev试试，稍等

**Comment by hackape** [comment]
有没有更多上下文？光看这个不能定位问题。

**Comment by hackape** [comment]
还有我刚有收到邮件看你还提到 lodash.isequal? 这个是什么情况，有相关信息我也想看看。

**Comment by yhl3692319** [comment]
我执行`sh ide.sh build`到最后报了这个错误

```
Hash: d6e78fda64071297cadc
Version: webpack 1.13.2
Time: 53166ms
      Asset       Size  Chunks             Chunk Names
    main.js    1.23 MB       0  [emitted]  main
     1.1.js    4.48 MB       1  [emitted]  
 index.html  753 bytes          [emitted]  
favicon.ico    4.29 kB          [emitted]  
    + 610 hidden modules

ERROR in ./~/css-loader?sourceMap!./~/sass-loader?sourceMap!./app/styles/main.scss
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (~/WebIDE/frontend/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:237:31)
    at LazyResult.then (~/WebIDE/frontend/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:141:21)
    at processCss (~/WebIDE/frontend/node_modules/css-loader/lib/processCss.js:198:5)
    at Object.module.exports (~/WebIDE/frontend/node_modules/css-loader/lib/loader.js:24:2)
 @ ./app/styles/main.scss 4:14-141
Child html-webpack-plugin for "index.html":
        + 3 hidden modules
ide.sh: 58: ide.sh: mvn: not found
```

是mvn没装吗 @hackape

**Comment by vangie** [comment]
@yhl3692319 嗯，需要安装 maven

**Comment by yhl3692319** [comment]
@vangie 这一步应该是在执行`mvn`命令之前就报错了吧

```
Hash: d6e78fda64071297cadc
Version: webpack 1.13.2
Time: 51427ms
      Asset       Size  Chunks             Chunk Names
    main.js    1.23 MB       0  [emitted]  main
     1.1.js    4.48 MB       1  [emitted]  
 index.html  753 bytes          [emitted]  
favicon.ico    4.29 kB          [emitted]  
    + 610 hidden modules

ERROR in ./~/css-loader?sourceMap!./~/sass-loader?sourceMap!./app/styles/main.scss
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (~/WebIDE/frontend/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:237:31)
    at LazyResult.then (~/WebIDE/frontend/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:141:21)
    at processCss (~/WebIDE/frontend/node_modules/css-loader/lib/processCss.js:198:5)
    at Object.module.exports (~/WebIDE/frontend/node_modules/css-loader/lib/loader.js:24:2)
 @ ./app/styles/main.scss 4:14-141
Child html-webpack-plugin for "index.html":
        + 3 hidden modules
[INFO] Scanning for projects...
Downloading: http://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom


```

我`sudo apt-get install maven2`之后依旧报错啊

**Comment by vangie** [comment]
你这个是ubuntu吧，估计内置的nodejs版本太低了

**Comment by hackape** [comment]
@yhl3692319 看上去你 nodejs 的环境里面没有 Promise API，版本升到最新试试吧

**Comment by owtotwo** [comment]
require("es6-promise"); 我也是这个问题 应该是nodejs版本问题 但是依赖需求里没写清楚版本要求啊……

**Comment by yhl3692319** [comment]
@owtotwo @vangie @hackape 恩我把nodejs升级到5.6可以了
