### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by TainKung** [Coding/WebIDE#68]
失败位置：
```
./node_modules/cross-env/bin/cross-env.js NODE_ENV=production ./node_modules/webpack/bin/webpack.js --progress --colors
```

完整错误信息：
```
npm ERR! Linux 2.6.32-642.6.2.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! coding-web-ide@0.1.0 build: `./node_modules/cross-env/bin/cross-env.js NODE_ENV=production ./node_modules/webpack/bin/webpack.js --progress --colors`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the coding-web-ide@0.1.0 build script './node_modules/cross-env/bin/cross-env.js NODE_ENV=production ./node_modules/webpack/bin/webpack.js --progress --colors'.
```

请问如何解决？

**Comment by hackape** [comment]
这些信息基本什么都没说…
请尝试一下把 package.json 里面 scripts.build 改为如下再试试看
`"build": "NODE_ENV=production ./node_modules/webpack/bin/webpack.js --progress --colors"`

**Comment by TainKung** [comment]
./ide.sh build 已经成功运行了。但是 ./ide.sh run 又出错了…
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:20 min
[INFO] Finished at: 2016-11-10T18:42:10+08:00
[INFO] Final Memory: 38M/117M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.4.0.RELEASE:run (default-cli) on project backend: Could not exec java: Application finished with non-zero exit code: 137 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

re-run maven -e 的结果是
```
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.184 s
[INFO] Finished at: 2016-11-10T18:47:35+08:00
[INFO] Final Memory: 4M/11M
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/root/WebIDE/WebIDE). Please verify you invoked Maven from the correct directory. -> [Help 1]
org.apache.maven.lifecycle.MissingProjectException: The goal you specified requires a project to execute but there is no POM in this directory (/root/WebIDE/WebIDE). Please verify you invoked Maven from the correct directory.
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:84)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
```

**Comment by hackape** [comment]
@tanhe123 你看看这个？

**Comment by tanhe123** [comment]
看报错信息是没有安装正确 java，请确保 java 正确安装、JAVA_HOME 环境变量正确配置。
如果只是体验，可以先尝试 docker 版，使用 `docker run -p 8080:8080 -h webide --name webide webide/webide` 即可。

**Comment by TainKung** [comment]
理论上我能正确安装 maven 的话，JAVA 的环境应当是正常的呀。JAVA 有版本要求么？
```
[root@localhost ~]# mvn -v
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T00:41:47+08:00)
Maven home: /opt/apache-maven-3.3.9
Java version: 1.8.0_111, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.111-0.b15.el6_8.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "2.6.32-642.6.2.el6.x86_64", arch: "amd64", family: "unix"
```

PS: 其实想用 Docker，奈何因为一些原因无法升级内核。

**Comment by tanhe123** [comment]
尝试执行：

```
cd backend
mvn spring-boot:run
```

然后把详细的错误信息发来吧

**Comment by TainKung** [comment]
附输出文件
[mvn.txt](https://github.com/Coding/WebIDE/files/587050/mvn.txt)

PS：是和那个 Atmosphere Framework 有关系？

**Comment by tanhe123** [comment]
从日志来看是启动成功了，然后被中断了，比如 ctrl+c？

当现实如下信息的时候，就可以打开浏览器，访问 `http://localhost:8080` 了（如果使用 ctrl+ c 会停止服务）。
```
2016-11-12 13:19:45.404  INFO 12207 --- [       Thread-3] org.atmosphere.cpr.AtmosphereFramework   : Latest version of Atmosphere's JavaScript Client 2.3.1
2016-11-12 13:19:45.405  INFO 12207 --- [       Thread-3] org.atmosphere.cpr.AtmosphereFramework   :

	Atmosphere Framework Updates:
	Major Update available (new features): 2.4.7
2016-11-12 13:19:49.809  INFO 12207 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring FrameworkServlet 'dispatcherServlet'
2016-11-12 13:19:49.811  INFO 12207 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization started
2016-11-12 13:19:49.828  INFO 12207 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 17 ms
2016-11-12 13:20:38.437  INFO 12207 --- [MessageBroker-1] o.s.w.s.c.WebSocketMessageBrokerStats    : WebSocketSession[0 current WS(0)-HttpStream(0)-HttpPoll(0), 0 total, 0 closed abnormally (0 connect failure, 0 send limit, 0 transport error)], stompSubProtocol[processed CONNECT(0)-CONNECTED(0)-DISCONNECT(0)], stompBrokerRelay[null], inboundChannel[pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], outboundChannelpool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], sockJsScheduler[pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]
```

**Comment by TainKung** [comment]
运行 mvn spring-boot:run 的确出现了你描述的结果。但是我还是不能正常运行 ./ide.sh run，单运行 mvn 那句就足够了么？此外，可以修改默认开放的端口么？

**Comment by tanhe123** [comment]
1. mvn spring-boot:run 正常，打开浏览器访问下页面试试？./ide.sh run 和 mvn spring-boot:run 完成的一样的功能，使用哪种方式都可以。
2. 端口可以修改，修改方式也很多，比如使用 maven 命令：mvn spring-boot:run -Drun.arguments="--server.port=8089"，又或者使用 ./ide.sh run -p 8089

**Comment by TainKung** [comment]
刚完成 mvn 的时候试过了，页面正常（但是 Terminal > New Terminal 貌似不能用？），但是 ./ide.sh run 就会报我之前的 BUILD FAILURE

**Comment by tanhe123** [comment]
1. Terminal > New Terminal 的问题 @hackape 
2. 那个错误是不全的，没看到有用的错误信息，麻烦你附一下完整的 log

**Comment by TainKung** [comment]
标准输出是这个[ide.txt](https://github.com/Coding/WebIDE/files/587304/ide.txt)

这个貌似是 mvn 的错误日志(?)，也放上来吧[hs_err_pid28519.txt](https://github.com/Coding/WebIDE/files/587305/hs_err_pid28519.txt)

**Comment by vangie** [comment]
@TainKung 错误显示，内存不足
```
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000fc57e000, 30605312, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 30605312 bytes for committing reserved memory.
# An error report file with more information is saved as:
```

**Comment by TainKung** [comment]
不是说 512M 可以跑的么。刚开 top 看了一下，从 611052k free 开始最后还是内存爆掉了…

**Comment by tanhe123** [comment]
问题修了，可以尝试更新下代码，然后再试下

```
 ./ide.sh run
```
