### ISSUE TITLE
因内存不足，Terminal 无法使用

### ISSUE THREAD

**Issue by TainKung** [Coding/WebIDE#70]
1. 可以通过按钮正常新建、关闭 Terminal 窗口，但通过 Tools > Terminal > New Terminal 新建终端时没有任何反应。
2. 如下图，Terminal 不显示提示符，且无法输入任何字符。
![coding webide - coding net](https://cloud.githubusercontent.com/assets/20412636/20261813/1d6c1252-aa25-11e6-9055-1e55e05445f1.gif)

**Comment by TainKung** [comment]
检查输出发现可能与内存不足有关。出现此错误时服务器有 50000 - 60000k 空闲内存。附部分输出：
```
exec_pty(54): returning due to error: Cannot allocate memory
java.io.IOException: Exec_tty error:Unknown reason
	at com.pty4j.unix.UnixPtyProcess.execInPty(UnixPtyProcess.java:235)
	at com.pty4j.unix.UnixPtyProcess.<init>(UnixPtyProcess.java:69)
	at com.pty4j.PtyProcess.exec(PtyProcess.java:79)
	at com.pty4j.PtyProcess.exec(PtyProcess.java:50)
	at net.coding.ide.tty.TerminalEmulator.<init>(TerminalEmulator.java:37)
	at net.coding.ide.tty.SocketIOHandler.itermOpen(SocketIOHandler.java:141)
	at net.coding.ide.tty.SocketIOHandler.onMessage(SocketIOHandler.java:74)
	at org.atmosphere.socketio.transport.SocketIOSessionManagerImpl$SessionImpl.onMessage(SocketIOSessionManagerImpl.java:383)
	at org.atmosphere.socketio.cpr.SocketIOWebSocketEventListener.onMessage(SocketIOWebSocketEventListener.java:72)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.notifyListener(DefaultWebSocketProcessor.java:747)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:470)
	at org.atmosphere.container.JSR356Endpoint$3.onMessage(JSR356Endpoint.java:260)
	at org.atmosphere.container.JSR356Endpoint$3.onMessage(JSR356Endpoint.java:257)
	at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:399)
	at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:106)
	at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:500)
	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:295)
	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:131)
	at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:69)
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148)
	at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:785)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1425)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by tanhe123** [comment]
如果条件允许，还是希望能增加内存。512M 内存对 java web 还是有些捉襟见肘的。
